### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'blocks'

### ISSUE THREAD

**Issue by XuanxiangHuang** [eth-sri/mn-bab#9]
Hello,

Thank you for your work.

I tried to run the example but failed. Do you know how to address this issue?

```
python src/verify.py -c configs/baseline/cifar10_conv_small.json

Device Info:

Python Version:
3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0]

Torch Version:
1.13.1+cu117
CUDA Version:
11.7
CUDA PATH:
None
CUDA Home:
None

Traceback (most recent call last):
  File "src/verify.py", line 49, in <module>
    original_network = load_net(**config.network.load_params())
  File "/home/xuanxiang/mn-bab/src/utilities/loading/network.py", line 811, in load_net
    original_network = original_network.blocks
  File "/home/xuanxiang/miniconda3/envs/MNBAB/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'blocks'
```

Many thanks!

**Comment by kkaulen** [comment]
This should be fixed in my PR #10
